--Dox List: 
--"0715008499462;0715008685334;0715008271937;0715008742747;0715008686829"

declare @max_index int
       ,@sql nvarchar(2000)

set @sql = 'SELECT @max_index = count(*) - 1 FROM NCO_FATTURAZIONEDETTAGLIO WHERE IDBATCH = 395 and IDCONVENZIONATA = 12040229'
exec sp_executesql @sql, N'@max_index int output', @max_index output

SELECT 
 'FAT' 'TIPO DOCUMENTO'
,'015' 'TIPO SERVIZIO FATTURATO'
,FD.ID_FATTURA 'N. FATTURA'
,'0000000' 'N. FATTURA ORIGINE'
,'000000001' 'N. LOTTO'
,CASE WHEN (ROW_NUMBER() OVER(PARTITION BY P.ROW_INDEX ORDER BY P.ROW) - 1) = 0 then '011127259'  else '' END 'CODICE FORNITORE' 
,CASE WHEN (ROW_NUMBER() OVER(PARTITION BY P.ROW_INDEX ORDER BY P.ROW) - 1) <> 0 then FD.RIFERIMENTO else '' END 'N. AUTORIZZAZIONE ARVAL'
,CASE WHEN (ROW_NUMBER() OVER(PARTITION BY P.ROW_INDEX ORDER BY P.ROW) - 1) <> 0 then FD.DOSSIER  else '' END 'DOSSIER VAI'
,CONVERT(VARCHAR(10), FD.DATA_FATTURA, 103) + ' 00:00' 'DATA FATTURA'
,'                ' 'DATA FATTURA ORIGINE'
,SUBSTRING(P.TIPO_ADDEBITO,0,4) 'CODICE TIPO ADDEBITO'
,FD.ATTIVITA 'DESCRIZIONE ADDEBITO (MAX 80 CARATTERI)'
,CASE SUBSTRING(P.TIPO_ADDEBITO,0,4) 
	WHEN 'TST' then CONVERT(numeric(8,2),FD.IMPORTO  * 1.22) --Iva
	WHEN 'RE1' then FD.IMPORTO_SOCC
	WHEN 'DEP' then FD.IMPORTO_DEP
	WHEN 'RE3' then IMPORTO_REC + IMPORTO_SUPPL
	else 0
 END 'IMPORTO'
,CASE WHEN (ROW_NUMBER() OVER(PARTITION BY P.ROW_INDEX ORDER BY P.ROW) - 1) = 0 then ''  else '22' END 'ALIQUOTA IVA'
,CASE WHEN (ROW_NUMBER() OVER(PARTITION BY P.ROW_INDEX ORDER BY P.ROW) - 1) = 0 then ''  else upper(VHL.vchNumberPlate) END 'TARGA'
,CASE WHEN (ROW_NUMBER() OVER(PARTITION BY P.ROW_INDEX ORDER BY P.ROW) - 1) = 0 then '' else '1,00' END 'QUANTITA'''
,'                                   ' 'EMPTY 1'
,'                                   ' 'EMPTY 2'
,'                                   ' 'EMPTY 3'
,CASE WHEN (ROW_NUMBER() OVER(PARTITION BY P.ROW_INDEX ORDER BY P.ROW) - 1) = 0 then ';;' else ';;;;' END 'TAIL'
FROM
(SELECT 
    ROWID
   ,DOSSIER
   ,ROW_NUMBER() OVER(ORDER BY ROWID) AS ROW
   ,ROW_NUMBER() OVER(ORDER BY ROWID) % (1 + @max_index) AS ROW_INDEX
   ,IMPORTO TST
   ,IMPORTO_SOCC RE1
   ,IMPORTO_USC
   ,IMPORTO_KM
   ,IMPORTO_DEP DEP
   ,IMPORTO_REC RE31
   ,IMPORTO_SUPPL RE3
FROM NCO_FATTURAZIONEDETTAGLIO
WHERE 
IDBATCH = 395
and IDCONVENZIONATA = 12040229
) FD
UNPIVOT(SOMMA for TIPO_ADDEBITO in
  (TST
  ,RE1
  ,IMPORTO_USC
  ,IMPORTO_KM
  ,DEP
  ,RE31
  ,RE3)
) AS P
left join NCO_FATTURAZIONEDETTAGLIO FD on P.ROWID = FD.ROWID 
left JOIN NCO_INCARICOCONVENZIONATA IC on IC.ID_DOSSIER = FD.IDDOX and IC.ID_INCARICOCONVENZIONATA = FD.ID_INCARICO
INNER JOIN Incident AS INC
  ON (INC.iIncidentId = FD.IDDENUNCIA)
INNER JOIN Individual AS IND
  ON (FD.IDINTESTATARIO = IND.iIndividualId)
INNER JOIN CSuExtensionRecord AS EX
  ON (INC.iIncidentId = EX.iSystemId
  AND INC.iSiteId = EX.iSiteId
  AND EX.iTableId = 128)
INNER JOIN NCO_Vehicle AS VHL
  ON VHL.iVehicleId = EX.iUserExtension2
WHERE 
FD.IDBATCH = 395
and FD.IDCONVENZIONATA = 12040229
and P.SOMMA > 0
order BY p.ROW